version: '3.1'

services:

  db:
    build: .
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: cifraeasy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
