CREATE TABLE cifraeasy.CE_CATEGORY (
	
    ID SERIAL NOT NULL,
	CONSTRAINT PK_CATEGORY PRIMARY KEY (ID), 

	DESC_CATEGORY VARCHAR (30) NOT NULL
 );

CREATE TABLE cifraeasy.CE_SINGER (
	
    ID SERIAL NOT NULL,
	CONSTRAINT PK_SINGER PRIMARY KEY (ID),  

	NAME_SINGER VARCHAR (30) NOT NULL
 );

CREATE TABLE cifraeasy.CE_RHYTHM (
	
    ID SERIAL NOT NULL,
	CONSTRAINT PK_RHYTHM PRIMARY KEY (ID), 

	DESC_RHYTHM VARCHAR (30) NOT NULL
 );

CREATE TABLE cifraeasy.CE_PART_TYPE (
	
    ID SERIAL NOT NULL,
	CONSTRAINT PK_PART_TYPE PRIMARY KEY (ID), 

	DESC_PART_TYPE VARCHAR (15) NOT NULL
 );

CREATE TABLE cifraeasy.CE_VERSION (
	
    ID SERIAL NOT NULL,
	CONSTRAINT PK_VERSION PRIMARY KEY (ID),  

	DESC_VERSION VARCHAR (30) NOT NULL,
	TONE_VERSION VARCHAR (5) NOT NULL,
	CAPO_POS_VERSION VARCHAR (1),

	ID_RHYTHM BIGINT NOT NULL,
	CONSTRAINT FK_RHYTHM FOREIGN KEY (ID_RHYTHM) REFERENCES CE_RHYTHM (ID) 
 );

CREATE TABLE cifraeasy.CE_PART (
	
    ID SERIAL NOT NULL,
	CONSTRAINT PK_PART PRIMARY KEY (ID),  

	CHORDS_PART VARCHAR (60) NOT NULL,

	ID_PART_TYPE BIGINT NOT NULL,
	CONSTRAINT FK_PART_TYPE FOREIGN KEY (ID_PART_TYPE) REFERENCES CE_PART_TYPE (ID),
	
	ID_VERSION BIGINT NOT NULL,
	CONSTRAINT FK_VERSION FOREIGN KEY (ID_VERSION) REFERENCES CE_VERSION (ID) 
 );


CREATE TABLE cifraeasy.CE_MUSIC (
	
    ID SERIAL NOT NULL,
	CONSTRAINT PK_MUSIC PRIMARY KEY (ID),  

	NAME_MUSIC VARCHAR (30) NOT NULL,

	ID_SINGER BIGINT NOT NULL,
	CONSTRAINT FK_SINGER FOREIGN KEY (ID_SINGER) REFERENCES CE_SINGER (ID),

	ID_CATEGORY BIGINT NOT NULL,
	CONSTRAINT FK_CATEGORY FOREIGN KEY (ID_CATEGORY) REFERENCES CE_CATEGORY (ID),

	ID_VERSION BIGINT NOT NULL,
	CONSTRAINT FK_VERSION FOREIGN KEY (ID_VERSION) REFERENCES CE_PART (ID) 
 );