
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('Moda de viola');
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('Raiz');
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('Sertanejo');
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('Sertanejo Universitário');
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('Internacional');
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('Pop Rock');
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('Rock');
INSERT INTO CE_CATEGORY(DESC_CATEGORY) VALUES ('MPB');

INSERT INTO CE_PART_TYPE(DESC_PART_TYPE) VALUES ('Introdução');
INSERT INTO CE_PART_TYPE(DESC_PART_TYPE) VALUES ('Estrofe');
INSERT INTO CE_PART_TYPE(DESC_PART_TYPE) VALUES ('Pré Refrão');
INSERT INTO CE_PART_TYPE(DESC_PART_TYPE) VALUES ('Refrão');
INSERT INTO CE_PART_TYPE(DESC_PART_TYPE) VALUES ('Passagem');
INSERT INTO CE_PART_TYPE(DESC_PART_TYPE) VALUES ('Solo');

INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Toada');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Pagode de viola');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Cururu');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Guarânia (lenta)');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Guarânia (acelerada)');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Batida simples (rock)');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Bolero');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Bachata');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Vanerão');
INSERT INTO CE_RHYTHM(DESC_RHYTHM) VALUES ('Valsa');
