
INSERT INTO CE_SINGER(NAME_SINGER) VALUES('João Mineiro e Marciano');
INSERT INTO CE_VERSION(DESC_VERSION, TONE_VERSION, CAPO_POS_VERSION, ID_RHYTHM) VALUES('Original', NULL, NULL, 4);
INSERT INTO CE_MUSIC(NAME_MUSIC, ID_SINGER, ID_CATEGORY, ID_VERSION) VALUES('Ainda Ontem Chorei de Saudade', 1, 2, 1);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('<C – Dm – G7>(2x) – C – G7 – C – C7 – F(2x) – C – G7 – C', 1, 1, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('C – Am – <Dm – G>(2x) – C – G', 2, 1, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('C(3x) – G(5x) – C – G – C(3x) – G(5x) – C – G', 4, 1, NULL);

INSERT INTO CE_SINGER(NAME_SINGER) VALUES('Kid Abelha');
INSERT INTO CE_VERSION(DESC_VERSION, TONE_VERSION, CAPO_POS_VERSION, ID_RHYTHM) VALUES('Simplificada', NULL, NULL, 6);
INSERT INTO CE_MUSIC(NAME_MUSIC, ID_SINGER, ID_CATEGORY, ID_VERSION) VALUES('Como Eu Quero', 2, 6, 2);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('Dm – F – C – G – Dm – F – C(2x)', 1, 2, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('C – G – Am – F - C – G – Am – F(2x)', 2, 2, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('Am – Em – F(2x)', 4, 2, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('C – G – Am – F - C – G – Am – F(2x)', 2, 2, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('Am – Em – F(2x)', 4, 2, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('Dm – F – C – G – Dm – F – C', 2, 2, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('Am – Em – F(2x)', 4, 2, NULL);

INSERT INTO CE_VERSION(DESC_VERSION, TONE_VERSION, CAPO_POS_VERSION, ID_RHYTHM) VALUES('Original', NULL, NULL, 10);
INSERT INTO CE_MUSIC(NAME_MUSIC, ID_SINGER, ID_CATEGORY, ID_VERSION) VALUES('Minha Serenata', 1, 2, 3);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('G – D – G(2x) – D – C – G(2x) – D – C – G(4x) – D(2x)', 2, 3, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('G – D – G(2x) – D – C – G(2x) – D – C – G(4x) – D(2x) – C – D – G(4x)', 2, 3, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('<C – G>(4x) – D(8x) – G', 4, 3, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('G – C', 5, 3, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('G – D – G(2x) – D – C – G(2x) – D – C – G(4x) – D(2x) – C – D – G(4x)', 2, 3, NULL);
INSERT INTO CE_PART(CHORDS_PART, ID_PART_TYPE, ID_VERSION, ID_RHYTHM) VALUES('<C – G>(4x) – D(8x) – G', 4, 3, NULL);
